In [2]:
# !pip install igraph

In [3]:
!pip show torch

Name: torch
Version: 2.2.1+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: d:\ProgramData\Anaconda3\envs\pth-gpu\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: axial-positional-embedding, CoLT5-attention, local-attention, product-key-memory, reformer-pytorch, torchvision


In [1]:
%%time
%run run_graph_notears.py

D:\DTemp\git\mamintoosi-papers-codes\GraphNOTEARS\GraphNOTEARS_syn_p_1\utils.py:352: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:620.)
  A = torch.sparse.FloatTensor(i, v, torch.Size([n, n])).to_dense()


b***********************
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
a**********************
[[-0.    -0.     0.    -1.179  0.     0.     0.    -0.     0.    -0.   ]
 [ 0.    -0.    -0.     0.557  0.    -0.     0.    -0.     0.    -0.   ]
 [-0.     0.     0.    -0.    -0.    -1.584  0.     0.     0.    -0.   ]
 [-1.744  0.     0.    -0.     0.    -0.633  0.    -0.    -0.    -0.   ]
 [-0.     0.     0.     0.     0.     0.    -0.    -0.     0.    -0.   ]
 [ 0.     0.    -0.    -0.     0.     0.    -0.    -0.     0.     0.   ]
 [-0.    -0.     0.    -0.    -0.     0.     0.    -0.341 -0.    -0.   ]
 [-0.678  0.    -0.     0.    -0.    -0.     0.     0.     0.     0.   ]
 [-0.     0.     0.     0.324  0.   

In [3]:
# !pip install openpyxl

In [1]:
%%time
%run run.py

D:\DTemp\git\mamintoosi-papers-codes\GraphNOTEARS\GraphNOTEARS_syn_p_1\utils.py:352: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:620.)
  A = torch.sparse.FloatTensor(i, v, torch.Size([n, n])).to_dense()


b***********************
[[1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1.]]
a**********************
[[-1.678  1.846  0.    -0.     0.288]
 [-0.    -0.    -0.701 -0.     0.   ]
 [-0.756  0.    -0.    -0.     0.   ]
 [ 0.     0.    -0.     0.808 -0.984]
 [-1.807 -0.     0.451  0.     1.887]]
[[ 1.  1.  0. -0.  1.]
 [-0. -0.  1. -0.  0.]
 [ 1.  0. -0. -0.  0.]
 [ 0.  0. -0.  1.  1.]
 [ 1. -0.  1.  0.  1.]]
p1_mat [[-1.678  1.846  0.    -0.     0.288]
 [-0.    -0.    -0.701 -0.     0.   ]
 [-0.756  0.    -0.    -0.     0.   ]
 [ 0.     0.    -0.     0.808 -0.984]
 [-1.807 -0.     0.451  0.     1.887]]
 n= 20 d= 5 s0= 5 w_graph_type = ER p_graph_type = ER sem_type = exp

-----model_p2-----
W_est: threshold = 0.3 fdr = 0.17 tpr = 1.00 fpr = 0.05 shd = 1.00 nnz = 6  f1 = 0.9090909090909091

P1_est: threshold = 0.3 acc =  fdr = 0.23 tpr = 1.00 fpr = 0.20 shd = 3.00 nnz = 13  f1 = 0.8695652173913043

-----notears + lasso-----
W_est: threshold = 0.3 fdr = 

In [3]:
# !pip install dagma

In [4]:
# P1_est_

In [3]:
%%time
%run GraphNOTEARS.py

w_true [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
w_mat [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5760750688906028, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.6878006889449602, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7419566804736037, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7597374935328408, 0.0, 0.0

TypeError: generate_tri() missing 3 required positional arguments: 'graph_type', 'low_value', and 'high_value'

CPU times: total: 109 ms
Wall time: 129 ms


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')