In [3]:
# !pip install igraph

In [4]:
%%time
%run run.py

b*********************** [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]]
a********************** [[ 0.     0.     0.    -0.     0.   ]
 [-0.     1.371  1.971  0.199  0.761]
 [-0.    -0.    -1.108  0.24  -0.   ]
 [-0.    -0.    -1.876  1.984  0.   ]
 [-0.    -0.    -0.     0.886 -0.   ]]
p1_mat [[ 0.     0.     0.    -0.     0.   ]
 [-0.     1.371  1.971  0.199  0.761]
 [-0.    -0.    -1.108  0.24  -0.   ]
 [-0.    -0.    -1.876  1.984  0.   ]
 [-0.    -0.    -0.     0.886 -0.   ]]
 n= 20 d= 5 s0= 5 w_graph_type = ER p_graph_type = ER sem_type = exp



AssertionError: Torch not compiled with CUDA enabled

CPU times: total: 328 ms
Wall time: 205 ms


In [3]:
%%time
%run GraphNOTEARS.py

w_true [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
w_mat [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5760750688906028, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.6878006889449602, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7419566804736037, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7597374935328408, 0.0, 0.0

TypeError: generate_tri() missing 3 required positional arguments: 'graph_type', 'low_value', and 'high_value'

CPU times: total: 109 ms
Wall time: 129 ms


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')